#!/usr/bin/python

import os
import optparse

parser = optparse.OptionParser(usage='%prog [options]')

parser.add_option(
    '-l',
    '--local-dirs',
    action='store_true',
    dest='use_local_dirs',
    help='Use files from the local directory tree.'
)
parser.add_option(
    '-d',
    '--debug',
    action='store_true',
    dest='use_debug',
    help='Enable debug mode.'
)
parser.add_option(
    '-e',
    '--session',
    action='store_true',
    dest='use_session',
    help='Use the standard configuration file for the per-login-session daemon.'
)
parser.add_option(
    '-y',
    '--system',
    action='store_true',
    dest='use_system',
    help='Use the standard configuration file for the systemwide daemon.'
)
parser.add_option(
    '-p',
    '--port',
    dest='port',
    help='Listen on the specified port. 804 by default for the systemwide daemon and 8004 for the per-login-session daemon.'
)

(options, args) = parser.parse_args()

if options.use_local_dirs:
    os.environ.setdefault('JPD_HTDOCS_PATH', 'htdocs/')
    os.environ.setdefault('JPD_ICONS_PATH', 'icons/')
else:
    os.environ.setdefault('JPD_HTDOCS_PATH', '/usr/share/jolicloud-daemon/htdocs/')
    os.environ.setdefault('JPD_ICONS_PATH', '/usr/share/jolicloud-daemon/icons/')

if options.use_debug:
    os.environ.setdefault('JPD_DEBUG', '1')

os.environ.setdefault('JPD_SESSION', '1')
if options.use_system:
    os.environ.setdefault('JPD_SYSTEM', '1')

if options.port:
    os.environ.setdefault('JPD_PORT', options.port)

from jolicloud_daemon.main import start

start()
