#!/usr/bin/env python

import os
import sys
import ConfigParser

config_file = '/etc/jolicloud-displaymanager/99jolicloud-autologin'

config = ConfigParser.RawConfigParser()
if os.path.exists(config_file):
    config.read(config_file)
    
if sys.argv[1] == 'status':
    if config.has_section('autologin') and config.getboolean('autologin', 'enabled') == True:
        print 'enabled'
    else:
        print 'disabled'
    exit(0)
elif sys.argv[1] == 'enable' and len(sys.argv[2]):
    if not config.has_section('autologin'):
        config.add_section('autologin')
    config.set('autologin', 'enabled', True)
    config.set('autologin', 'login', sys.argv[2])
    config.write(open(config_file, 'w'))
    exit(0)
elif sys.argv[1] == 'disable':
    if not config.has_section('autologin'):
        config.add_section('autologin')
    config.set('autologin', 'enabled', False)
    config.write(open(config_file, 'w'))
    exit(0)

exit(42)
