#!/usr/bin/env python

import os
import sys
import ConfigParser

config_file = '/etc/jolicloud-displaymanager/99jolicloud-guestmode'

config = ConfigParser.RawConfigParser()
if os.path.exists(config_file):
    config.read(config_file)

if sys.argv[1] == 'status':
    if config.has_section('guestmode') and config.getboolean('guestmode', 'enabled') == True:
        print 'enabled'
    else:
        print 'disabled'
    exit(0)
elif sys.argv[1] == 'enable':
    if not config.has_section('guestmode'):
        config.add_section('guestmode')
    config.set('guestmode', 'enabled', True)
    config.set('guestmode', 'login', 'guest')
    config.set('guestmode', 'group', 'guests')
    config.set('guestmode', 'logincmd', 'exec /bin/bash -login /usr/share/jolicloud-guestlogin/start-session')
    config.write(open(config_file, 'w'))
    os.system('pam-auth-update --package')
    exit(0)
elif sys.argv[1] == 'disable':
    if not config.has_section('guestmode'):
        config.add_section('guestmode')
    config.set('guestmode', 'enabled', False)
    config.write(open(config_file, 'w'))
    os.system('pam-auth-update --remove guestlogin')
    exit(0)

exit(42)
