#!/bin/bash

slim_conf=/etc/slim.conf
args=("$@")

if [ "${args[0]}" = "status" ]; then
    if STATUS=`egrep "^guest_group\s*guests\$" "$slim_conf"`; then
        echo "enabled"
    else
        echo "disabled"
    fi
    exit 0
elif [ "${args[0]}" = "enable" ]; then

    if ! CONF_ENTRY=`grep ^guest_ $slim_conf` 2>/dev/null; then
	echo "guest_group guests" >> $slim_conf
	echo "login_guest_cmd exec /bin/bash -login /usr/share/jolicloud-guestlogin/start-session %session" >> $slim_conf
	pam-auth-update --package
    fi
    exit $?
elif [ "${args[0]}" = "disable" ]; then
    sed -ibackup -r \
        -e "/^#?guest_group.*\$/d" \
        -e "/^#?login_guest_cmd.*\$/d" \
        $slim_conf
    pam-auth-update --remove guestlogin
    exit $?
fi

exit 42
